#!/usr/bin/env bash

lake run scout --command tactics --read lake run scout --command tactics --read .lake/packages/mathlib/Mathlib/Algebra/Prime/Lemmas.lean

uv run python make_tactic_summary.py
uv run python build_site.py